PROJECT:  g12
TRACK:  test
JOBNAME:  g12_simulation_XXX.VVV
COMMAND:  generatescript_XXX.VVV
OTHER_FILES: DDD/generatescript_XXX.VVV
INPUT_FILES: 
DDD/genr8input_XXX.VVV
DDD/ffread.g12
ADD/ANA
OUTPUT_DATA: ANA.root
OUTPUT_TEMPLATE: OOO/MC_XXX.VVV.a1c.root
OUTPUT_DATA: work.gamp.root
OUTPUT_TEMPLATE: OOO/MC_XXX.VVV.gamp.root
SINGLE_JOB: true
DISK_SPACE: 1 GB
TIME: 400
MEMORY: 500 MB
CPU: 3