PROJECT:  g12
TRACK:  test
JOBNAME:  g12_simulation_XXX.VVV
COMMAND:  generatescript_XXX.VVV
OTHER_FILES: DDD/generatescript_XXX.VVV
INPUT_FILES: 
DDD/genr8input_XXX.VVV
DDD/ffread.g12
ADD/ANA
OUTPUT_DATA: work.gamp
OUTPUT_TEMPLATE: OOO/MC_XXX.VVV.gamp
OUTPUT_DATA: work.part
OUTPUT_TEMPLATE: OOO/MC_XXX.VVV.part
OUTPUT_DATA: work.gsim
OUTPUT_TEMPLATE: OOO/MC_XXX.VVV.gsim
OUTPUT_DATA: work.gpp
OUTPUT_TEMPLATE: OOO/MC_XXX.VVV.gpp
OUTPUT_DATA: gpp.hbook
OUTPUT_TEMPLATE: OOO/MC_XXX.VVV.hbook
OUTPUT_DATA: work.a1c
OUTPUT_TEMPLATE: OOO/MC_XXX.VVV.a1c
OUTPUT_DATA: ANA.view
OUTPUT_TEMPLATE: OOO/MC_XXX.VVV.view
OUTPUT_DATA: ANA.lab
OUTPUT_TEMPLATE: OOO/MC_XXX.VVV.lab
OUTPUT_DATA: ANA.C
OUTPUT_TEMPLATE: OOO/MC_XXX.VVV.C
OUTPUT_DATA: ANA.root
OUTPUT_TEMPLATE: OOO/MC_XXX.VVV.a1c.root
OUTPUT_DATA: work.gamp.root
OUTPUT_TEMPLATE: OOO/MC_XXX.VVV.gamp.root
SINGLE_JOB: true
DISK_SPACE: 1 GB
TIME: 400
MEMORY: 500 MB
CPU: 2