PROJECT:  g12
TRACK:  simulation
JOBNAME:  g12_debug2_simulation_XXX.VVV
COMMAND:  generatescript_XXX.VVV
OTHER_FILES: DDD/generatescript_XXX.VVV
INPUT_FILES: 
DDD/genr8input_XXX.VVV
DDD/ffread.g12
ADD/RED
ADD/PLR
ADD/ANA
ADD/BNB
ADD/GGG


OUTPUT_DATA: gpp2kppim.root
OUTPUT_TEMPLATE: OOO/MC-TEST-ANA-XXX.VVV.root


SINGLE_JOB: true
DISK_SPACE: 5 GB
TIME: 1100
MEMORY: 500 MB