#! /usr/bin/perl
$filelist=$ARGV[0];
$dir=`pwd`;
chop($dir);
open(A, "$filelist");
while(<A>){
	chop;
	$file=$_;
	if($file=~ /\b(.*?)\.KpKp/){
		$viewfile=$1.".kpkppim.view";
		$cmd="$dir/g112kppim -X1 -C1 -F1 -p1 -aviewfiles/$viewfile data/$file";
		#print "$cmd\n";
		system("$cmd");
	}
}
